# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pyqt5
          pip install --upgrade -I pip setuptools importlib-metadata==4.12 pytest
          python setup.py install
          pip install -I PyQt5
          pip install --upgrade -I sip
          pip install --upgrade -I PyQt5-sip
      - name: Test with pytest
        run: |
          pytest -vv
